### ISSUE TITLE
Scapegoat analysis results not captured in SonarQube

### ISSUE THREAD

**Issue by goldsworthy** [mwz/sbt-sonar#12]
I took the multi-module test project and added code which successfully triggered ScapeGoat. However, this information was not pushed up to SonarQube. I would expect to see the warnings under code smells, as I do for ScalaStyle issues. 

https://github.com/mwz/sbt-sonar/tree/master/src/sbt-test/sbt-sonar/multi-module

I'm running SonarQube 6.7.5

**Comment by mwz** [comment]
Hi @goldsworthy, we're aware of an issue with the scapegoat sensor and multi module projects, which we're tracking in sonar-scala project (https://github.com/mwz/sonar-scala/issues/92). Please keep an eye on this issue - I'm hoping to fix it pretty soon.

**Comment by mwz** [comment]
Here is the hotfix https://github.com/mwz/sonar-scala/pull/96 - I should be able to release it relatively quickly once the PR gets reviewed.

**Comment by mwz** [comment]
Hi @goldsworthy, would you be able to give [6.5.1](https://github.com/mwz/sonar-scala/releases/tag/v6.5.1) a try and let us know if that fixes the issue for you?

**Comment by goldsworthy** [comment]
@mwz I installed the 6.5.1 plugin and tested this with the example project and my own project. I'm not seeing the scapegoat information in SonarQube for either project. Please let me know if there is any other information I can provide.

**Comment by BalmungSan** [comment]
Hi @goldsworthy, that's strange

Could you provide us with the debug logs of the test project run.

**Comment by BalmungSan** [comment]
@goldsworthy I think I [found your problem](https://gist.github.com/goldsworthy/44e497fc93d8486884d351a122967123#file-gistfile1-txt-L262).

If you were using the [old scapegoat plugin](https://github.com/arthepsy/sonar-scala-extra) those rules are no longer valid, since this is a new plugin, so you should update your quality profile.

PS: If you want you can use the default Scapegoat quality profile that the plugin provides, just for testing 😉 

Hope it helped :+1:.

**Comment by goldsworthy** [comment]
@mwz @BalmungSan I can confirm this is working properly - your help and responsiveness is greatly appreciated!

**Comment by mwz** [comment]
That's excellent, I'm glad we got to the bottom of it - thanks @BalmungSan for jumping in!

@goldsworthy, the best thing you can do for now is to create a new profile with scalastyle and scapegoat rules (if you want to use both). In the near future, we're planning to provide both a combined profile (Scalastyle + Scapegoat) along with a recommended profile, so this should be easier to set up.

It also looks like SonarSource will be working on official support for Scala later this year, so watch out this space.

**Comment by h-ngo** [comment]
@mwz 
Encountered a similar issue in multi-module gradle project. According to the logs (see below with masked module/class named due to business restrictions), it looks like the reported was loaded, but issues are not reported as code smell in Sonar (there are violations in the html that scapegoat generated).

Any ideas? Thanks in advance :)

sonarqube: 6.7.7 - sonar-scala: 6.8.0

Logs (file not found errors are Spec files. No other scapegoat related errrors):

09:27:44.626 [INFO] [org.sonarqube.gradle.SonarQubeTask] [sonar-scala-scapegoat] Loading the scapegoat report file: '/export/home/dev/IdeaProjects/abc-app-scapegoat/abc-business/build/scapegoat/scapegoat.xml'.
09:27:44.626 [DEBUG] [org.sonarqube.gradle.SonarQubeTask] [sonar-scala-scapegoat] The current working directory is: '/export/home/dev/IdeaProjects/abc-app-scapegoat'.
09:27:44.631 [INFO] [org.sonarqube.gradle.SonarQubeTask] [sonar-scala-scapegoat] Successfully loaded the scapegoat report file.
09:27:44.631 [INFO] [org.sonarqube.gradle.SonarQubeTask] [sonar-scala-scapegoat] Saving the scapegoat issues for file 'src/test/scala/abc/flow/MS/MSFlowSpec.scala'.
09:27:44.632 [ERROR] [org.sonarqube.gradle.SonarQubeTask] [sonar-scala-scapegoat] The file 'src/test/scala/abc/flow/MS/MSFlowSpec.scala' couldn't be found.
09:27:44.632 [INFO] [org.sonarqube.gradle.SonarQubeTask] [sonar-scala-scapegoat] Saving the scapegoat issues for file 'src/test/scala/abc/flow/MP/MPFlowSpec.scala'.
09:27:44.632 [ERROR] [org.sonarqube.gradle.SonarQubeTask] [sonar-scala-scapegoat] The file 'src/test/scala/abc/flow/MP/MPFlowSpec.scala' couldn't be found.
09:27:44.632 [INFO] [org.sonarqube.gradle.SonarQubeTask] [sonar-scala-scapegoat] Saving the scapegoat issues for file 'src/test/scala/abc/flow/DS/DSFlowSpec.scala'.
09:27:44.633 [ERROR] [org.sonarqube.gradle.SonarQubeTask] [sonar-scala-scapegoat] The file 'src/test/scala/abc/flow/DS/DSFlowSpec.scala' couldn't be found.
09:27:44.633 [INFO] [org.sonarqube.gradle.SonarQubeTask] [sonar-scala-scapegoat] Saving the scapegoat issues for file 'src/test/scala/abc/flow/MP/MPValidatorSpec.scala'.
09:27:44.633 [ERROR] [org.sonarqube.gradle.SonarQubeTask] [sonar-scala-scapegoat] The file 'src/test/scala/abc/flow/MP/MPValidatorSpec.scala' couldn't be found.
09:27:44.633 [INFO] [org.sonarqube.gradle.SonarQubeTask] [sonar-scala-scapegoat] Saving the scapegoat issues for file 'src/test/scala/abc/flow/MU/MUValidatorSpec.scala'.
09:27:44.634 [ERROR] [org.sonarqube.gradle.SonarQubeTask] [sonar-scala-scapegoat] The file 'src/test/scala/abc/flow/MU/MUValidatorSpec.scala' couldn't be found.
09:27:44.634 [INFO] [org.sonarqube.gradle.SonarQubeTask] [sonar-scala-scapegoat] Saving the scapegoat issues for file 'src/test/scala/abc/flow/DR/DRFlowSpec.scala'.
09:27:44.634 [ERROR] [org.sonarqube.gradle.SonarQubeTask] [sonar-scala-scapegoat] The file 'src/test/scala/abc/flow/DR/DRFlowSpec.scala' couldn't be found.
09:27:44.634 [INFO] [org.sonarqube.gradle.SonarQubeTask] [sonar-scala-scapegoat] Saving the scapegoat issues for file 'src/test/scala/abc/flow/MU/MUFlowSpec.scala'.
09:27:44.635 [ERROR] [org.sonarqube.gradle.SonarQubeTask] [sonar-scala-scapegoat] The file 'src/test/scala/abc/flow/MU/MUFlowSpec.scala' couldn't be found.
09:27:44.635 [INFO] [org.sonarqube.gradle.SonarQubeTask] [sonar-scala-scapegoat] Saving the scapegoat issues for file 'src/test/scala/abc/flow/DS/DSRollbackSpec.scala'.
09:27:44.635 [ERROR] [org.sonarqube.gradle.SonarQubeTask] [sonar-scala-scapegoat] The file 'src/test/scala/abc/flow/DS/DSRollbackSpec.scala' couldn't be found.
09:27:44.635 [INFO] [org.sonarqube.gradle.SonarQubeTask] Sensor Scapegoat Sensor [scala] (done) | time=9ms
